// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTracker.BE.DB.DataAccess;

#nullable disable

namespace TimeTracker.BE.DB.Migrations
{
    [DbContext(typeof(MainDatacontext))]
    partial class MainDatacontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("TimeTracker.BE.DB.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Activity_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Activities", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Start"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pause"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stop"
                        });
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Project_ID");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Project", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Project 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Project 2"
                        });
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.RecordActivity", b =>
                {
                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid_ID");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Activity_ID");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("End_DateTime");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Project_ID");

                    b.Property<Guid?>("ShiftGuidId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Shift_GuidID");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("Start_DateTime");

                    b.Property<int?>("SubModuleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SubModule_ID");

                    b.Property<int?>("TypeShiftId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TypeShift_ID");

                    b.HasKey("GuidId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ShiftGuidId");

                    b.HasIndex("SubModuleId");

                    b.HasIndex("TypeShiftId");

                    b.ToTable("Record_activities", "dbo");

                    b.HasData(
                        new
                        {
                            GuidId = new Guid("307e0d2d-abc2-40b3-9663-cd236f5c53db"),
                            ActivityId = 1,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 1, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 11, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("5e98e2d5-93b1-4f35-8eb9-d789660de4f8"),
                            ActivityId = 2,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 11, 1, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("1ddf6371-a203-4fcf-8939-3d19df766ea2"),
                            ActivityId = 1,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("3fddf2c2-54d2-4fd5-9294-ab7c58b6ddef"),
                            ActivityId = 3,
                            Description = "",
                            StartDateTime = new DateTime(2024, 11, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("38eb2448-95c2-4843-93c9-e33f2bea0a9c"),
                            ActivityId = 1,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 2, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 11, 2, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("e02c5199-6ceb-4678-9e53-af0a5b5a7e22"),
                            ActivityId = 2,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 11, 2, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("a90c2641-92f5-4986-a329-bf0fae490fa0"),
                            ActivityId = 1,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("cca64427-625d-4d11-9c1c-5143f2379776"),
                            ActivityId = 3,
                            Description = "",
                            StartDateTime = new DateTime(2024, 11, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("6aca049f-10b4-4a18-96fa-d6a4859b7274"),
                            ActivityId = 1,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 3, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 2,
                            StartDateTime = new DateTime(2024, 11, 3, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("3c8f8cbb-4c10-4db3-a237-a68dafbcb4c7"),
                            ActivityId = 2,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 11, 3, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("7b1e2806-fe98-4f9e-82f3-44b07681f43b"),
                            ActivityId = 1,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 11, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("237c6e29-3ae6-4189-9779-badece04410e"),
                            ActivityId = 3,
                            Description = "",
                            StartDateTime = new DateTime(2024, 11, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("d666ef9e-3635-45a9-b8f1-6011ef77a25c"),
                            ActivityId = 1,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 4, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1,
                            StartDateTime = new DateTime(2024, 11, 4, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            SubModuleId = 1,
                            TypeShiftId = 2
                        },
                        new
                        {
                            GuidId = new Guid("b3340d72-36d7-4638-b4e7-82c7ba3d05d1"),
                            ActivityId = 2,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 11, 4, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 2
                        },
                        new
                        {
                            GuidId = new Guid("57422b84-6a3e-4742-88fe-661f1a8ea6e7"),
                            ActivityId = 1,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 4, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 11, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 2
                        },
                        new
                        {
                            GuidId = new Guid("3de6e8bf-c83c-482d-aa01-ca9588c4e256"),
                            ActivityId = 3,
                            Description = "",
                            StartDateTime = new DateTime(2024, 11, 4, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 2
                        },
                        new
                        {
                            GuidId = new Guid("b1aeed02-a169-4d75-9cbf-17b15b810a12"),
                            ActivityId = 1,
                            Description = "Test poznamky",
                            EndDateTime = new DateTime(2024, 11, 5, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1,
                            ShiftGuidId = new Guid("d434a034-f93d-4f68-a69a-60243a16d21d"),
                            StartDateTime = new DateTime(2024, 11, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 3
                        },
                        new
                        {
                            GuidId = new Guid("7854a46a-f9c7-48d6-a9d8-19a35ed407aa"),
                            ActivityId = 2,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 11, 5, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 3
                        },
                        new
                        {
                            GuidId = new Guid("c3adb288-7f5c-46dd-8eba-54e972946586"),
                            ActivityId = 1,
                            Description = "",
                            EndDateTime = new DateTime(2024, 11, 5, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 11, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 3
                        },
                        new
                        {
                            GuidId = new Guid("1e12e58c-ab12-4944-94af-4cb4f9164d55"),
                            ActivityId = 3,
                            Description = "",
                            StartDateTime = new DateTime(2024, 11, 5, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 3
                        });
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.Shift", b =>
                {
                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid_ID");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShiftGuidId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Start_date");

                    b.Property<int>("TypeShiftId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TypeShift_ID");

                    b.HasKey("GuidId");

                    b.HasIndex("ShiftGuidId");

                    b.HasIndex("StartDate")
                        .IsUnique();

                    b.HasIndex("TypeShiftId");

                    b.ToTable("Shifts", "dbo", t =>
                        {
                            t.HasComment("Tabulka slouží k naplánování směny.");
                        });

                    b.HasData(
                        new
                        {
                            GuidId = new Guid("fa1db3cb-f2c4-4efd-aee9-cd3487366229"),
                            StartDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("9ad8ec6d-6bd8-4cf5-b681-c46c86c508f3"),
                            StartDate = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("d917a220-5a2c-401c-90cc-c746aaada412"),
                            StartDate = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 2
                        },
                        new
                        {
                            GuidId = new Guid("68dbc51a-9546-4450-bf46-e614397021e4"),
                            StartDate = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 2
                        },
                        new
                        {
                            GuidId = new Guid("31402227-1064-4455-872f-df218a85aca3"),
                            StartDate = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("d434a034-f93d-4f68-a69a-60243a16d21d"),
                            StartDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("a634ce0f-ab0c-4061-babb-70f656277fa1"),
                            StartDate = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 3
                        },
                        new
                        {
                            GuidId = new Guid("865370c2-1115-4b23-b4c9-f7cdebbbe86d"),
                            StartDate = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        },
                        new
                        {
                            GuidId = new Guid("a9f6f060-c255-43e5-b5d5-e9d7860ab14d"),
                            StartDate = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 2
                        },
                        new
                        {
                            GuidId = new Guid("d10f4bf4-c1a4-404b-9213-803ad4cee509"),
                            StartDate = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeShiftId = 1
                        });
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.SubModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("SubModule_ID");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Project_ID");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("SubModule", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SubModule 1",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "SubModule 2",
                            ProjectId = 1
                        });
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.TypeShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TypeShift_ID");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisibleInMainWindow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int?>("TypeShiftId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeShiftId");

                    b.ToTable("TypeShifts", "dbo", t =>
                        {
                            t.HasComment("Tabulka všech možných směn.");
                        });

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Color = "SkyBlue",
                            IsVisibleInMainWindow = true,
                            Name = "HomeOffice"
                        },
                        new
                        {
                            Id = 1,
                            Color = "Orange",
                            IsVisibleInMainWindow = true,
                            Name = "Office"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Magenta",
                            IsVisibleInMainWindow = true,
                            Name = "Others"
                        },
                        new
                        {
                            Id = 4,
                            Color = "LawnGreen",
                            IsVisibleInMainWindow = false,
                            Name = "Holiday"
                        });
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.RecordActivity", b =>
                {
                    b.HasOne("TimeTracker.BE.DB.Models.Activity", "Activity")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeTracker.BE.DB.Models.Project", "Project")
                        .WithMany("Activities")
                        .HasForeignKey("ProjectId");

                    b.HasOne("TimeTracker.BE.DB.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftGuidId");

                    b.HasOne("TimeTracker.BE.DB.Models.SubModule", "SubModule")
                        .WithMany("Activities")
                        .HasForeignKey("SubModuleId");

                    b.HasOne("TimeTracker.BE.DB.Models.TypeShift", "TypeShift")
                        .WithMany("RecordActivity")
                        .HasForeignKey("TypeShiftId");

                    b.Navigation("Activity");

                    b.Navigation("Project");

                    b.Navigation("Shift");

                    b.Navigation("SubModule");

                    b.Navigation("TypeShift");
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.Shift", b =>
                {
                    b.HasOne("TimeTracker.BE.DB.Models.Shift", null)
                        .WithMany("Shifts")
                        .HasForeignKey("ShiftGuidId");

                    b.HasOne("TimeTracker.BE.DB.Models.TypeShift", "TypeShift")
                        .WithMany()
                        .HasForeignKey("TypeShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeShift");
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.SubModule", b =>
                {
                    b.HasOne("TimeTracker.BE.DB.Models.Project", "Project")
                        .WithMany("SubModules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.TypeShift", b =>
                {
                    b.HasOne("TimeTracker.BE.DB.Models.TypeShift", null)
                        .WithMany("TypeShifts")
                        .HasForeignKey("TypeShiftId");
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.Activity", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.Project", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("SubModules");
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.Shift", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.SubModule", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("TimeTracker.BE.DB.Models.TypeShift", b =>
                {
                    b.Navigation("RecordActivity");

                    b.Navigation("TypeShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
